dist: bionic

language: php

php:
  - 7.0
  - 7.1

services:
  - mysql

before_script:
  - mysql -e 'create database testing;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --seed

script:
  - vendor/bin/phpunit

notifications:
email:
  recipients:
    - thelabdevtz@gmal.com
  on_success: always
  on_failure: always